[input]
html_selector = "main"
base_directory = "/home/emkeyen/Blog/pyblog2/utput"

[[input.files]]
path = "postman-to-jmeter-converter.html"
url = "/https://github.com/emkeyen/postman-to-jmx"
title = "Converting Postman collections with env support to JMeter"

[[input.files]]
path = "go-server-rest-api-test.html"
url = "/go-server-rest-api-test.html"
title = "Building & Testing a REST API in Go using httpserver, httptest, testing & testify"
